"""Capture real WCF session-mode messages as test fixtures.

Development-only (pythonnet + .NET Framework + csc).  Compiles a throwaway
DataContract assembly, runs three messages through WCF's own binary *session*
encoder, and writes the bytes to ``tests/golden/session_messages.json``.

The point is to freeze how the session dictionary evolves: message 1 carries a
populated new-strings block, messages 2 and 3 carry an empty one and refer to
those strings by id.  Bugs in that state machine do not show up on the first
message, so a golden fixture per *message* is what catches them.

    python tools/gen_session_fixtures.py

Nothing here touches any production service -- the contract is local and
invented for the test.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "golden" / "session_messages.json"

CSC = Path(os.environ.get("WINDIR", r"C:\Windows")) / "Microsoft.NET" / "Framework64" / "v4.0.30319" / "csc.exe"

CONTRACT = """
using System.Runtime.Serialization;

namespace DemoNs
{
    [DataContract(Namespace = "urn:DemoService")]
    public class LeaveRequest
    {
        [DataMember(Order = 0)] public string EmployeeId { get; set; }
        [DataMember(Order = 1)] public string ReasonText { get; set; }
        [DataMember(Order = 2)] public int TotalDays { get; set; }
    }
}
"""

ACTION = "urn:DemoService/create"
TO = "net.tcp://localhost:8000/Demo"


def build_contract(workdir: Path) -> Path:
    source = workdir / "DemoContract.cs"
    source.write_text(CONTRACT, encoding="utf-8")
    dll = workdir / "DemoContract.dll"
    if not CSC.is_file():
        sys.exit(f"C# compiler not found at {CSC}")
    subprocess.run(
        [str(CSC), "-nologo", "-target:library", f"-out:{dll}", str(source)],
        check=True,
        capture_output=True,
    )
    return dll


def main() -> None:
    # The CLR keeps a lock on an assembly once loaded, so the temp directory
    # cannot be removed while this process lives -- leave the remains behind
    # rather than failing after the fixtures have already been produced.
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        dll = build_contract(Path(tmp))

        import clr  # type: ignore
        import System  # type: ignore

        clr.AddReference("System.ServiceModel")
        clr.AddReference(str(dll))

        from DemoNs import LeaveRequest  # type: ignore
        from System import Uri  # type: ignore
        from System.ServiceModel.Channels import (  # type: ignore
            BinaryMessageEncodingBindingElement,
            BufferManager,
            Message,
            MessageVersion,
        )

        encoder = BinaryMessageEncodingBindingElement().CreateMessageEncoderFactory().CreateSessionEncoder()
        buffers = BufferManager.CreateBufferManager(System.Int64(1 << 20), 1 << 16)

        messages = []
        for n in (1, 2, 3):
            body = LeaveRequest()
            body.EmployeeId = f"E{n}"
            body.ReasonText = "Personal"
            body.TotalDays = n

            message = Message.CreateMessage(MessageVersion.Soap12WSAddressing10, ACTION, body)
            message.Headers.To = Uri(TO)

            segment = encoder.WriteMessage(message, 1 << 16, buffers, 0)
            raw = bytearray(segment.Array)[segment.Offset:segment.Offset + segment.Count]
            messages.append({"employee_id": f"E{n}", "total_days": n, "hex": bytes(raw).hex()})

    fixture = {
        "_comment": (
            "Real WCF application/soap+msbinsession1 messages. Generated by "
            "tools/gen_session_fixtures.py against a local throwaway DataContract; "
            "no production service involved."
        ),
        "content_type": "application/soap+msbinsession1",
        "action": ACTION,
        "to": TO,
        "expected_session_strings": [
            "LeaveRequest",
            "urn:DemoService",
            "http://www.w3.org/2001/XMLSchema-instance",
            "EmployeeId",
            "ReasonText",
            "TotalDays",
        ],
        "messages": messages,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {OUT}")
    for i, message in enumerate(messages, 1):
        raw = bytes.fromhex(message["hex"])
        print(f"  msg{i}: {len(raw):4} bytes, block prefix 0x{raw[0]:02x}")


if __name__ == "__main__":
    main()
